"""create cv_analyses table

Revision ID: 01a790add6c8
Revises: 56013ffd90c6
Create Date: 2026-06-07 00:49:55.670330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a790add6c8'
down_revision = '56013ffd90c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('diplomas', sa.Text(), nullable=True),
    sa.Column('experiences', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('cv_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cv_id'], ['cvs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cv_analyses')
    # ### end Alembic commands ###
