"""Migration vers heritage polymorphique

Revision ID: 0c2cb32c5bf8
Revises: 3a34d99f20a9
Create Date: 2026-06-28 15:59:18.519046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c2cb32c5bf8'
down_revision = '3a34d99f20a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruteurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('entreprise_id IS NOT NULL', name='check_recruteur_has_entreprise_strict'),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_departement_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('users_entreprise_id_fkey'), type_='foreignkey')
        batch_op.drop_column('departement_id')
        batch_op.drop_column('entreprise_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entreprise_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('departement_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('users_entreprise_id_fkey'), 'entreprises', ['entreprise_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('users_departement_id_fkey'), 'departements', ['departement_id'], ['id'], ondelete='SET NULL')

    op.drop_table('candidats')
    op.drop_table('recruteurs')
    # ### end Alembic commands ###
