"""coorection des liaisons de la table des questions d'entretien. 

Revision ID: 3721f93ab044
Revises: ddd83deaeced
Create Date: 2026-07-06 12:36:12.280892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3721f93ab044'
down_revision = 'ddd83deaeced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions_entretien', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('questions_entretien_offre_id_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions_entretien', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('questions_entretien_offre_id_key'), ['offre_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
