"""Restructuration du matching en table Candidature avec statut RH

Revision ID: 381b3895d91b
Revises: 6859b478b129
Create Date: 2026-06-26 19:31:54.070364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '381b3895d91b'
down_revision = '6859b478b129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('matching_skills', sa.JSON(), nullable=True),
    sa.Column('missing_skills', sa.JSON(), nullable=True),
    sa.Column('extra_skills', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cv_analyser_id', sa.Integer(), nullable=False),
    sa.Column('offre_analyser_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cv_analyser_id'], ['cv_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offre_analyser_id'], ['offre_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidatures')
    # ### end Alembic commands ###
