""" Ajout de la table LesRecrutEntreprise

Revision ID: 3a34d99f20a9
Revises: 4a7d8bcd8548
Create Date: 2026-06-28 14:14:50.231226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a34d99f20a9'
down_revision = '4a7d8bcd8548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('les_recrut_entreprise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_recrutement', sa.DateTime(), nullable=False),
    sa.Column('type_contrat', sa.String(length=50), nullable=False),
    sa.Column('salaire_propose', sa.Float(), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('offre_id', sa.Integer(), nullable=False),
    sa.Column('candidat_id', sa.Integer(), nullable=False),
    sa.Column('match_result_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['candidat_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_result_id'], ['match_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['offre_id'], ['offres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('les_recrut_entreprise')
    # ### end Alembic commands ###
