"""Correction de la table candidature

Revision ID: 4a7d8bcd8548
Revises: 381b3895d91b
Create Date: 2026-06-26 19:51:10.627851

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a7d8bcd8548'
down_revision = '381b3895d91b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidatures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offre_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('match_result_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('candidatures_offre_analyser_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('candidatures_cv_analyser_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'offres', ['offre_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'match_results', ['match_result_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('recommendation')
        batch_op.drop_column('extra_skills')
        batch_op.drop_column('offre_analyser_id')
        batch_op.drop_column('score')
        batch_op.drop_column('missing_skills')
        batch_op.drop_column('matching_skills')
        batch_op.drop_column('cv_analyser_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidatures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_analyser_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('matching_skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('missing_skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('offre_analyser_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('extra_skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('recommendation', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('candidatures_cv_analyser_id_fkey'), 'cv_analyses', ['cv_analyser_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('candidatures_offre_analyser_id_fkey'), 'offre_analyses', ['offre_analyser_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('match_result_id')
        batch_op.drop_column('offre_id')

    # ### end Alembic commands ###
