"""create cvs table

Revision ID: 56013ffd90c6
Revises: d2f57b12be2b
Create Date: 2026-06-06 17:06:05.276659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56013ffd90c6'
down_revision = 'd2f57b12be2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cvs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_fichier', sa.String(length=255), nullable=False),
    sa.Column('chemin_fichier', sa.String(length=500), nullable=False),
    sa.Column('contenu_texte', sa.Text(), nullable=True),
    sa.Column('date_upload', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cvs')
    # ### end Alembic commands ###
