"""Initiation des migrations

Revision ID: 573e75729854
Revises: 
Create Date: 2026-07-01 09:10:19.277122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573e75729854'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entreprises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('site_web', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), nullable=False),
    sa.Column('derniere_connexion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('candidats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['utilisateurs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recruteurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('entreprise_id IS NOT NULL', name='check_recruteur_has_entreprise_strict'),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id'], ['utilisateurs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cvs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_fichier', sa.String(length=255), nullable=False),
    sa.Column('chemin_fichier', sa.String(length=500), nullable=False),
    sa.Column('contenu_texte', sa.Text(), nullable=True),
    sa.Column('date_upload', sa.DateTime(timezone=True), nullable=False),
    sa.Column('est_actif', sa.Boolean(), nullable=False),
    sa.Column('candidat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidat_id'], ['candidats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('nom_fichier', sa.String(length=255), nullable=False),
    sa.Column('chemin_fichier', sa.String(length=500), nullable=False),
    sa.Column('contenu_texte', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_limite', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recruteur_id', sa.Integer(), nullable=False),
    sa.Column('departement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recruteur_id'], ['recruteurs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('offre_id', sa.Integer(), nullable=False),
    sa.Column('cv_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cv_id'], ['cvs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offre_id'], ['offres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cv_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competences', sa.JSON(), nullable=True),
    sa.Column('diplomes', sa.JSON(), nullable=True),
    sa.Column('experiences', sa.JSON(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cv_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cv_id'], ['cvs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cv_id')
    )
    op.create_table('offre_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competences', sa.JSON(), nullable=True),
    sa.Column('diplomes', sa.JSON(), nullable=True),
    sa.Column('experiences', sa.JSON(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), nullable=False),
    sa.Column('offre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['offre_id'], ['offres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offre_id')
    )
    op.create_table('les_recrut_entreprise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_recrutement', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type_contrat', sa.String(length=50), nullable=False),
    sa.Column('salaire_propose', sa.Float(), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('candidature_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidature_id'], ['candidatures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cv_analyser_id', sa.Integer(), nullable=False),
    sa.Column('offre_analyser_id', sa.Integer(), nullable=False),
    sa.Column('competences_validees', sa.JSON(), nullable=True),
    sa.Column('competences_manquantes', sa.JSON(), nullable=True),
    sa.Column('competences_bonus', sa.JSON(), nullable=True),
    sa.Column('diplomes_valides', sa.JSON(), nullable=True),
    sa.Column('diplomes_manquants', sa.JSON(), nullable=True),
    sa.Column('experiences_validees', sa.JSON(), nullable=True),
    sa.Column('experiences_manquantes', sa.JSON(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('recommandation', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cv_analyser_id'], ['cv_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offre_analyser_id'], ['offre_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_results')
    op.drop_table('les_recrut_entreprise')
    op.drop_table('offre_analyses')
    op.drop_table('cv_analyses')
    op.drop_table('candidatures')
    op.drop_table('offres')
    op.drop_table('cvs')
    op.drop_table('recruteurs')
    op.drop_table('departements')
    op.drop_table('candidats')
    op.drop_table('utilisateurs')
    op.drop_table('entreprises')
    # ### end Alembic commands ###
