"""Ajout de la colonne date_limite

Revision ID: 6859b478b129
Revises: 60976e266b49
Create Date: 2026-06-25 21:32:03.393102

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6859b478b129'
down_revision = '60976e266b49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_limite', sa.DateTime(timezone=True), nullable=False))
        batch_op.alter_column('date_creation',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offres', schema=None) as batch_op:
        batch_op.alter_column('date_creation',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.drop_column('date_limite')

    # ### end Alembic commands ###
