"""correction de la table des questions d'entretien. 

Revision ID: 6eb58d42fdf6
Revises: 3721f93ab044
Create Date: 2026-07-06 13:20:59.609321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb58d42fdf6'
down_revision = '3721f93ab044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions_entretien', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donnees_json', sa.Text(), nullable=True))
        batch_op.alter_column('categorie',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('texte_question',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions_entretien', schema=None) as batch_op:
        batch_op.alter_column('texte_question',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('categorie',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('donnees_json')

    # ### end Alembic commands ###
