"""create offre_analysis table

Revision ID: 7ab9d35cfa79
Revises: a5dba60dc5d3
Create Date: 2026-06-10 23:16:28.296437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ab9d35cfa79'
down_revision = 'a5dba60dc5d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offre_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('diplomas', sa.Text(), nullable=True),
    sa.Column('experiences', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('offre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['offre_id'], ['offres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('offre_analyses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offre_analyses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('skills', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('diplomas', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('experiences', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('offre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['offre_id'], ['offres.id'], name=op.f('offre_analyses_offre_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('offre_analyses_pkey'))
    )
    op.drop_table('offre_analysis')
    # ### end Alembic commands ###
