"""mise à jour de la relation LesRecrutEntreprise

Revision ID: 905e227b747b
Revises: 573e75729854
Create Date: 2026-07-01 14:58:58.339669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905e227b747b'
down_revision = '573e75729854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv_analyses', schema=None) as batch_op:
        batch_op.drop_column('score')

    with op.batch_alter_table('les_recrut_entreprise', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['candidature_id'])
        batch_op.drop_constraint(batch_op.f('les_recrut_entreprise_entreprise_id_fkey'), type_='foreignkey')
        batch_op.drop_column('entreprise_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('les_recrut_entreprise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entreprise_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('les_recrut_entreprise_entreprise_id_fkey'), 'entreprises', ['entreprise_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('cv_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
