"""Revision de la relation de candidature

Revision ID: 98ee9c1c7c42
Revises: bd2863264c01
Create Date: 2026-06-30 07:02:57.168375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ee9c1c7c42'
down_revision = 'bd2863264c01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidatures', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('candidatures_candidat_id_fkey'), type_='foreignkey')
        batch_op.drop_column('candidat_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidatures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidat_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('candidatures_candidat_id_fkey'), 'candidats', ['candidat_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
