"""Ajout de la class entretien

Revision ID: a45f850e91bd
Revises: 905e227b747b
Create Date: 2026-07-02 02:04:02.785369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a45f850e91bd'
down_revision = '905e227b747b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entretiens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_rendezvous', sa.Date(), nullable=False),
    sa.Column('heure_rendezvous', sa.Time(), nullable=False),
    sa.Column('lieu', sa.String(length=255), nullable=False),
    sa.Column('statut_entretien', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), nullable=False),
    sa.Column('candidature_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidature_id'], ['candidatures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entretiens')
    # ### end Alembic commands ###
