"""Ajout la table des questions d'entretien. 

Revision ID: ddd83deaeced
Revises: fb121dac1c6c
Create Date: 2026-07-06 12:29:40.167125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd83deaeced'
down_revision = 'fb121dac1c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions_entretien',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offre_id', sa.Integer(), nullable=False),
    sa.Column('categorie', sa.String(length=50), nullable=False),
    sa.Column('texte_question', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['offre_id'], ['offres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offre_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions_entretien')
    # ### end Alembic commands ###
