"""Mise a jour des modeles CV, Offre et leurs analyses

Revision ID: fa43a7cbdd44
Revises: 3d9044e554b6
Create Date: 2026-06-18 00:27:04.391181

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa43a7cbdd44'
down_revision = '3d9044e554b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offre_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('diplomas', sa.JSON(), nullable=True),
    sa.Column('experiences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('offre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['offre_id'], ['offres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offre_id')
    )
    op.drop_table('offre_analysis')
    with op.batch_alter_table('cv_analyses', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['cv_id'])
        batch_op.drop_constraint(batch_op.f('cv_analyses_cv_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'cvs', ['cv_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('offres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nom_fichier', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('chemin_fichier', sa.String(length=500), nullable=False))
        batch_op.alter_column('date_creation',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('offres_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offres', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('offres_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.alter_column('date_creation',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('chemin_fichier')
        batch_op.drop_column('nom_fichier')

    with op.batch_alter_table('cv_analyses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cv_analyses_cv_id_fkey'), 'cvs', ['cv_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    op.create_table('offre_analysis',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('skills', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('diplomas', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('experiences', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('offre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['offre_id'], ['offres.id'], name=op.f('offre_analysis_offre_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('offre_analysis_pkey'))
    )
    op.drop_table('offre_analyses')
    # ### end Alembic commands ###
