"""Déplacement des contenus textuelles dans les synthèse des document

Revision ID: fb121dac1c6c
Revises: a45f850e91bd
Create Date: 2026-07-05 09:10:56.360949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb121dac1c6c'
down_revision = 'a45f850e91bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contenu_texte', sa.Text(), nullable=True))

    with op.batch_alter_table('cvs', schema=None) as batch_op:
        batch_op.drop_column('contenu_texte')

    with op.batch_alter_table('offre_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contenu_texte', sa.Text(), nullable=True))

    with op.batch_alter_table('offres', schema=None) as batch_op:
        batch_op.drop_column('contenu_texte')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contenu_texte', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('offre_analyses', schema=None) as batch_op:
        batch_op.drop_column('contenu_texte')

    with op.batch_alter_table('cvs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contenu_texte', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('cv_analyses', schema=None) as batch_op:
        batch_op.drop_column('contenu_texte')

    # ### end Alembic commands ###
